const CHANGE_DRAWER = "CHANGE_DRAWER";
const SAVE_TOKEN = "SAVE_TOKEN";
const SAVE_PHONE = "SAVE_PHONE";
const SAVE_CITIES = "SAVE_CITIES";

export { CHANGE_DRAWER, SAVE_TOKEN, SAVE_PHONE, SAVE_CITIES };
